version: '3'
services: 
    registry:
        image: registry:2
        ports: 
            - "80:5000"
        restart: always
        volumes: 
            - "registry-data:/var/lib/registry"
            - "./registry-config.yml:/etc/docker/registry/config.yml"
    redis:
        image: redis:alpine
        command: redis-server /etc/redis.conf
        volumes: 
            - "redis-data:/data"
            - "./redis.conf:/etc/redis.conf"
        ports: 
            - "6379"
        networks: 
            registry:
                ipv4_address: <WILL_BE_OVERRIDDEN>
volumes: 
    registry-data:
    redis-data:
networks: 
    registry:
        ipam:
            config: 
                - subnet: <WILL_BE_OVERRIDDEN>
