version: '3.7'
services: 
    registry:
        image: registry:2
        ports: 
            - "80:5000"
        restart: always
        volumes: 
            - type: volume
              source: registry-data
              target: /var/lib/registry
            - type: bind
              source: ./registry-config.yml
              target: /etc/docker/registry/config.yml
        networks: 
            registry:
                ipv4_address: 192.168.128.10
    redis:
        image: redis:alpine
        command: redis-server /etc/redis.conf
        volumes: 
            - type: volume
              source: redis-data
              target: /data
            - type: bind
              source: ./redis.conf
              target: /etc/redis.conf
        ports: 
            - "6379"
        networks: 
            registry:
                ipv4_address: 192.168.128.11
volumes: 
    registry-data:
    redis-data:
networks: 
    registry:
        ipam:
            config: 
                - subnet: 192.168.128.0/24
